# Generated by Django 6.1 on 2026-08-12 20:08

import django.db.models.deletion
import mls_core.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mls_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Short code used in URLs, e.g. ENG', max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Optional emoji shown next to the space name', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wiki_spaces_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WikiPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('content_html', models.TextField(blank=True, help_text='Sanitized HTML from the rich text editor')),
                ('current_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classification', mls_core.fields.MLSForeignKey(help_text='Security classification for this page', mls_control=True, on_delete=django.db.models.deletion.PROTECT, related_name='wiki_pages', to='mls_core.securityclearance')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wiki_pages_created', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent page - leave blank for a top-level page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='wiki.wikipage')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='wiki.space')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wiki_pages_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='WikiAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='wiki_attachments/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('classification', mls_core.fields.MLSForeignKey(help_text="Security classification for this file - independent of the page's", mls_control=True, on_delete=django.db.models.deletion.PROTECT, related_name='wiki_attachments', to='mls_core.securityclearance')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wiki_attachments_uploaded', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='wiki.wikipage')),
            ],
            options={
                'ordering': ['filename'],
            },
        ),
        migrations.CreateModel(
            name='WikiRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('content_html', models.TextField(blank=True)),
                ('change_note', models.CharField(blank=True, max_length=255)),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wiki_revisions', to='mls_core.securityclearance')),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wiki_revisions', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='wiki.wikipage')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.AddConstraint(
            model_name='wikipage',
            constraint=models.UniqueConstraint(fields=('space', 'slug'), name='unique_page_slug_per_space'),
        ),
        migrations.AddConstraint(
            model_name='wikirevision',
            constraint=models.UniqueConstraint(fields=('page', 'version'), name='unique_revision_version_per_page'),
        ),
    ]
