# Generated by Django 5.2.7 on 2025-11-03 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Optional name for this clearance/classification', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of this clearance level')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Security Clearance',
                'verbose_name_plural': 'Security Clearances',
            },
        ),
        migrations.CreateModel(
            name='SecurityLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(help_text="Short code (e.g., 'TS', 'S', 'CRYPTO')", max_length=10, unique=True)),
                ('name', models.CharField(help_text='Full name of the label', max_length=100)),
                ('label_type', models.CharField(choices=[('LVL', 'Level'), ('CAT', 'Category')], default='CAT', help_text='Level (hierarchical) or Category (compartment)', max_length=3)),
                ('rank', models.IntegerField(default=0, help_text='For levels: higher rank = more sensitive. Categories ignore this.')),
                ('description', models.TextField(blank=True, help_text='Description of what this label means')),
                ('color', models.CharField(default='#808080', help_text='Color code for display (hex format)', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Security Label',
                'verbose_name_plural': 'Security Labels',
                'ordering': ['label_type', '-rank', 'name'],
                'permissions': [('manage_labels', 'Can manage security labels')],
            },
        ),
        migrations.CreateModel(
            name='DACGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_groups', models.ManyToManyField(blank=True, help_text='Parent groups (members inherit parent memberships)', related_name='child_dac_groups', to='mls_core.dacgroup')),
            ],
            options={
                'verbose_name': 'DAC Group',
                'verbose_name_plural': 'DAC Groups',
                'permissions': [('manage_dac_groups', 'Can manage DAC groups')],
            },
        ),
        migrations.CreateModel(
            name='MLSGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_groups', models.ManyToManyField(blank=True, help_text='Parent groups (members inherit parent clearances)', related_name='child_groups', to='mls_core.mlsgroup')),
                ('clearance_template', models.ForeignKey(help_text='Security clearance granted to group members', on_delete=django.db.models.deletion.PROTECT, related_name='mls_groups', to='mls_core.securityclearance')),
            ],
            options={
                'verbose_name': 'MLS Group',
                'verbose_name_plural': 'MLS Groups',
                'permissions': [('manage_mls_groups', 'Can manage MLS groups')],
            },
        ),
        migrations.AddField(
            model_name='securityclearance',
            name='securities',
            field=models.ManyToManyField(blank=True, help_text='The set of security labels', related_name='clearances', to='mls_core.securitylabel'),
        ),
        migrations.CreateModel(
            name='SecurityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clearance_expires', models.DateField(blank=True, help_text='Date when clearance expires (optional)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this security profile')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive profiles cannot access anything')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clearances', models.ForeignKey(blank=True, help_text='Direct security clearance (combined with group clearances)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='mls_core.securityclearance')),
                ('dac_groups', models.ManyToManyField(blank=True, help_text='DAC groups (OR logic for discretionary access)', related_name='members', to='mls_core.dacgroup')),
                ('mls_groups', models.ManyToManyField(blank=True, help_text='MLS groups (user gets ALL labels from ALL groups)', related_name='members', to='mls_core.mlsgroup')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Profile',
                'verbose_name_plural': 'Security Profiles',
                'permissions': [('security_manager', 'Security Manager - Can edit profiles and assign labels'), ('senior_security_manager', 'Senior Security Manager - Can CRUD all security objects')],
            },
        ),
    ]
