# Generated by Django 6.1 on 2026-08-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mls_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitylabel',
            name='label_type',
            field=models.CharField(choices=[('LVL', 'Level'), ('CAT', 'Category'), ('REL', 'Releasability')], default='CAT', help_text='Level (hierarchical), Category (compartment), or Releasability (country)', max_length=3),
        ),
    ]
