# Generated by Django 4.1.4 on 2022-12-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('LVL', 'Level'), ('CAT', 'Category')], default='CAT', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='FakeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('securities', models.ManyToManyField(to='abac.securitylabel')),
            ],
        ),
    ]
