# Generated by Django 4.1.4 on 2022-12-31 01:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('obj_type', models.CharField(choices=[('SHIP', 'Ship'), ('SUB', 'Submarine'), ('AC', 'Aircraft'), ('FILE', 'File')], default='SHIP', max_length=4)),
                ('x_coords', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100)])),
                ('y_coords', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.RenameField(
            model_name='securitylabel',
            old_name='type',
            new_name='label_type',
        ),
    ]
