# Generated by Django 4.1.4 on 2023-01-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abac', '0002_object_rename_type_securitylabel_label_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='securities',
            field=models.ManyToManyField(to='abac.securitylabel'),
        ),
    ]
