# Generated by Django 4.2.2 on 2023-06-07 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abac', '0003_object_securities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fakeuser',
            name='securities',
        ),
        migrations.RemoveField(
            model_name='object',
            name='securities',
        ),
        migrations.RenameModel(
            old_name='SecurityLabel',
            new_name='Label',
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('securities', models.ManyToManyField(default=1, null=True, related_name='labels', to='abac.label')),
            ],
            options={
                'verbose_name_plural': 'securities',
            },
        ),
        migrations.AddField(
            model_name='fakeuser',
            name='accesses',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='abac.security'),
        ),
        migrations.AddField(
            model_name='object',
            name='security',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='abac.security'),
            preserve_default=False,
        ),
    ]
