# Generated by Django 4.2.2 on 2023-06-07 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abac', '0004_remove_fakeuser_securities_remove_object_securities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='securities',
            field=models.ManyToManyField(null=True, related_name='labels', to='abac.label'),
        ),
    ]
