"""
Django settings for mls project.

Generated by 'django-admin startproject' using Django 4.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!v9t4t!g+0q$07*y79a^u($xhjv9uu1i&91%!w*(b7a*d+gzpi'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']  # Allow all hosts for Docker deployment

# CSRF trusted origins for production deployment
CSRF_TRUSTED_ORIGINS = [
    'https://mls.dev.thedonnelly.net',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'mls_core',
    'main.apps.MainConfig',
    'abac.apps.AbacConfig',
    'wiki.apps.WikiConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
# Add crum middle-ware for getting the current user in models
MIDDLEWARE += ('crum.CurrentRequestUserMiddleware',)

ROOT_URLCONF = 'mls.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mls.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Los_Angeles'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# MEDIA_ROOT holds uploaded files (wiki attachments). Deliberately NOT served
# at MEDIA_URL via Django's static() helper in urls.py - attachments carry
# their own MLS classification, so they must only ever be reachable through
# wiki's attachment_download view, which checks accessible_by() before
# streaming any bytes. A public MEDIA_URL mapping would let anyone with a
# guessed/leaked path fetch a classified file with zero access control.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# mls_core's test suite (test_metaclasses.py, tests.py, test_fields.py, ...)
# defines extra models purely for testing that are never added to a real
# migration. mls_core otherwise has migrations, so the test database would
# only get tables for what's in migrations, leaving those test-only models
# without a table ("no such table" at the first .create()/.save() call).
# Treating mls_core as unmigrated *only* for test runs makes Django build
# its test-database tables directly from whatever models are registered
# (including test-only ones) instead of replaying migration history - which
# is fine for tests, since they don't care about migration history, only
# about the resulting schema.
#
# wiki has to be listed here too: its migration legitimately depends on
# mls_core's ('wiki', '0001_initial') -> ('mls_core', '0001_initial'), and
# once mls_core is excluded from the graph that dependency dangles and
# breaks migration-graph resolution for every test, not just wiki's own.
# Any future app with a real migration dependency on mls_core needs adding
# here for the same reason.
import sys
if 'test' in sys.argv or 'pytest' in sys.modules:
    MIGRATION_MODULES = {'mls_core': None, 'wiki': None}
